
const icons = {
  casa: "bi bi-house",
  emitirNota: "bi bi-file-earmark-plus",
  clientePerson: "bi bi-person-circle",
  clientes: "bi bi-people",
  clientesAdd: "bi bi-person-add",
  produtos: "bi bi-box",
  produtosAdd: "bi bi-building-fill-add",
  produtoIdentidade: "bi bi-box-seam-fill",
  transporte: "bi bi-bus-front",
  cash: "bi bi-cash-coin",
  moeda: "bi bi-coin",
  relatorio: "bi bi-journal-text",
  relatorioAdd: "bi bi-journal-plus",
  relatorioOk: "bi bi-journal-check",
  planos: "bi bi-card-list",
  pagamento: "bi bi-credit-card",
  notificacoes: "bi bi-bell",
  feedback: "bi bi-chat-dots",
  feedbackTel: "bi bi-telephone-forward",
  ajuda: "bi bi-question-circle",
  sair: "bi bi-box-arrow-right",
  menuAberto: "bi bi-x",
  menuFechado: "bi bi-list",
  mapa: "bi bi-geo-alt-fill",
  edit: "bi bi-pencil-square",
  contador: "bi-calculator",
  duvidas: "bi bi-question-circle",
  configuracao: "bi bi-gear",
  celular: "bi bi-telephone",
  cadeado: "bi bi-lock",
  chave: "bi bi-key",
  suporte: "bi bi-headset",
  seguranca:"bi bi-shield-lock",
  cartao: "bi bi-credit-card",
  aparencia: "bi bi-palette"
};

export default icons;
